# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8050606816d76cc73da4aeae1f3700cb2bff0bf35bdf200a8f4f34cbca63399bd06f1b1f0386b3cab3f13cd77499344ea05013bcaa2906bfa003d17cfb73bf69

test:
  secret_key_base: b31f15ad4869a10e16aaeb91ab7d7fa508ea1496302a130664c790a6f7211217f12f200b760843b6bb052bda55d7b899793ea39175785b23150d9000c3fffbf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
